python -m torch.distributed.run --nnodes=1 --nproc_per_node=2 --max_restarts 1 train_cosine_loss.py \
                --arch "xcit_small_12_p16" \
                --batch_size_per_gpu 128 \
                --num_workers "6" \
                --images_root_dir "${MVMLDATA}/images" \
                --train_csv_path "${MVMLDATA}/splits/kaggle_shopee/product_idSplit_train.csv" \
                --test_csv_path "${MVMLDATA}/splits/kaggle_shopee/product_idSplit_test.csv" \
                --experiments_root_dir "${EXPERIMENTS}" \
                --experiment_name "DinoLinearCosine" \
                --run_name "xcit_small_12_p16" \
                --lr 0.005 \
                --val_freq 10
