python -m torch.distributed.run --nnodes=1 --nproc_per_node=2  main_dino.py --arch xcit_small_12_p16 \
                --data_path $MVMLDATA/images \
                --num_workers 6 \
                --experiments_root_dir $EXPERIMENTS \
                --experiment_name test \
                --run_name xcit_small_12_p16 \
                --credentials ~/.ssh/service_accounts/image-analysis-storage-admin.json \
                --xcit_pretrained 1 \
                --batch_size_per_gpu 12 \
                --warmup_epochs 0 \
                --lr 0.0001