python -m torch.distributed.run --nnodes=1 --nproc_per_node=2 --max_restarts 1 main_dino.py --arch xcit_small_12_p16 \
                --data_path $MVMLDATA/images \
                --num_workers 6 \
                --experiments_root_dir $EXPERIMENTS \
                --experiment_name Dino \
                --run_name xcit_small_12_p16 \
                --credentials ~/.ssh/service_accounts/image-analysis-storage-admin.json \
                --xcit_pretrained 1 \
                --batch_size_per_gpu 12 \
                --warmup_epochs 0 \
                --lr 0.003 \
		--epochs 8 \
                --freeze_last_layer 2 \
                --global_crops_scale 0.5 1.0
		--local_crops_scale 0.15 0.45 \
                --weight_decay_end 0.1 \
                --momentum_teacher 0.9995 \
                --teacher_temp 0.3
